### ISSUE TITLE
Documentation on how to run the app

### ISSUE THREAD

**Issue by andrey-yantsen** [dmontag23/rush#30]
Hey @dmontag23!

This repo looks like you were able to do a tremendous amount of work!

This week I'm on a theatre journey, trying to visit a play every day and not break the bank :) So far, my best attempt with TodayTix has ended with just a simple bash-script, showing me how many tickets are available/held for different shows.

Would you be open to telling more about your app, or just documenting how I can run it locally, please?

**Comment by dmontag23** [comment]
Hi @andrey-yantsen 👋  I set out to write this app with the intention of being able to improve the experience of getting rush tickets, but quickly found that the [official TodayTix app](https://www.todaytix.com/us/static/download) provides a much nicer experience. As a result I just continued to work on my app with the intention of learning react native while integrating to a real backend api, it doesn't actually do anything more than the TodayTix app itself. So I'd recommend use the official TodayTix app to get tickets for shows (I've only made this project public so I can use GitHub Actions without charge :-) )

**Comment by andrey-yantsen** [comment]
Wait, are you telling me that the API for Rush tickets is public, and I did some reverse engineering for nothing? :D I miss the numbers of available & held tickets being clearly displayed in the official app, and seeing those helped me not give up on a show tonight 😅 

Anyway, thank you for the prompt response, and good luck with React Native! ❤️
